---
task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 20
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset: 
    type: MultiDirCocoDetection  # Cambiado de CocoDetection a MultiDirCocoDetection
    image_dirs:
      - ./dataset/cleansea_dataset/train/
      - ./dataset/Ocean_garbage/train/
      - ./dataset/Ocean_garbage/valid/
      - ./dataset/Neural_Ocean/train/
      - ./dataset/Neural_Ocean/valid/
      - ./dataset/synthetic_dataset_v2/
    return_masks: False
    remap_mscoco_category: False
    transforms:
      type: Compose
      ops:
      
  shuffle: True
  num_workers: 0
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: MultiDirCocoDetection  # Cambiado de CocoDetection a MultiDirCocoDetection
    image_dirs:
      - ./dataset/cleansea_dataset/test/
      - ./dataset/Ocean_garbage/test/
      - ./dataset/Neural_Ocean/test/
    return_masks: False
    remap_mscoco_category: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 0
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
